name: Go

on: [push]

env:
  GOPATH: ${{ github.workspace }}/..

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go: [ '1.12.x', '1.13.x' ]
    steps:

    - name: Setup Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
      with:
        path: src/github.com/${{ github.repository }}

    - name: Unit test
      run: go test

    - name: Build
      run: go build
